SELECT DISTINCT INMUEBLE_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_DESCRIPCION, INMUEBLE_DIRECCION, [INMUEBLE_SUPERFICIETOTAL], 
[INMUEBLE_ANTIGUEDAD], [INMUEBLE_EXPESAS], [INMUEBLE_CARACTERISTICA_WIFI], [INMUEBLE_CARACTERISTICA_CABLE],
[INMUEBLE_CARACTERISTICA_CALEFACCION], [INMUEBLE_CARACTERISTICA_GAS], [INMUEBLE_BARRIO], [INMUEBLE_LOCALIDAD],
[INMUEBLE_PROVINCIA], [INMUEBLE_TIPO_INMUEBLE], [INMUEBLE_CANT_AMBIENTES], [INMUEBLE_ORIENTACION], [INMUEBLE_DISPOSICION],
[INMUEBLE_ESTADO]
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL 
/*AND INMUEBLE_CODIGO = 142577
ORDER BY INMUEBLE_CODIGO*/
SELECT *
FROM LOS_GESTIONADORES.Inmueble 

SELECT DISTINCT INMUEBLE_CODIGO, [INMUEBLE_ESTADO]
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL 
SELECT *
FROM LOS_GESTIONADORES.Estado_Inmueble

SELECT DISTINCT INMUEBLE_CODIGO, INMUEBLE_TIPO_INMUEBLE
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL 
SELECT * 
FROM LOS_GESTIONADORES.Tipo_Inmueble

SELECT DISTINCT INMUEBLE_CODIGO, INMUEBLE_CARACTERISTICA_CABLE, INMUEBLE_CARACTERISTICA_CALEFACCION, INMUEBLE_CARACTERISTICA_GAS,
INMUEBLE_CARACTERISTICA_WIFI
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL
SELECT *
FROM LOS_GESTIONADORES.Caracteristica

SELECT * 
FROM LOS_GESTIONADORES.Caracteristica_Inmueble

SELECT DISTINCT INMUEBLE_CODIGO, INMUEBLE_DISPOSICION
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL 
SELECT * 
FROM LOS_GESTIONADORES.Disposicion

SELECT DISTINCT INMUEBLE_CODIGO, INMUEBLE_ORIENTACION
FROM [gd_esquema].[Maestra]
WHERE INMUEBLE_CODIGO IS NOT NULL 
SELECT *
FROM LOS_GESTIONADORES.Orientacion

SELECT distinct [PROPIETARIO_DNI],PROPIETARIO_NOMBRE,[PROPIETARIO_APELLIDO], [PROPIETARIO_FECHA_REGISTRO], [PROPIETARIO_TELEFONO]
[PROPIETARIO_MAIL], [PROPIETARIO_FECHA_NAC]
FROM [gd_esquema].[Maestra]
WHERE PROPIETARIO_NOMBRE IS NOT NULL
select * from 
LOS_GESTIONADORES.Propietario 

SELECT distinct [ANUNCIO_CODIGO], [ANUNCIO_FECHA_PUBLICACION], [ANUNCIO_PRECIO_PUBLICADO], [ANUNCIO_COSTO_ANUNCIO],
[ANUNCIO_FECHA_FINALIZACION], [ANUNCIO_TIPO_OPERACION], [ANUNCIO_MONEDA], [ANUNCIO_ESTADO], [ANUNCIO_TIPO_PERIODO]
FROM [gd_esquema].[Maestra]
WHERE [ANUNCIO_CODIGO] IS NOT NULL
order by [ANUNCIO_CODIGO]
select * from LOS_GESTIONADORES.Anuncio 

SELECT distinct [ANUNCIO_CODIGO], [ANUNCIO_ESTADO]
FROM [gd_esquema].[Maestra]
WHERE [ANUNCIO_CODIGO] IS NOT NULL
order by [ANUNCIO_CODIGO]
select * from LOS_GESTIONADORES.Estado_Anuncio

select distinct ALQUILER_CODIGO, [ALQUILER_FECHA_INICIO], [ALQUILER_FECHA_FIN], [ALQUILER_CANT_PERIODOS], [ALQUILER_DEPOSITO]
[ALQUILER_COMISION], [ALQUILER_GASTOS_AVERIGUA]
from [gd_esquema].[Maestra]
WHERE ALQUILER_CODIGO IS NOT NULL
select * from LOS_GESTIONADORES.Alquiler

select distinct ALQUILER_CODIGO, [PAGO_ALQUILER_CODIGO], [PAGO_ALQUILER_FECHA], [PAGO_ALQUILER_FECHA_VENCIMIENTO],
[PAGO_ALQUILER_NRO_PERIODO], [PAGO_ALQUILER_DESC], [PAGO_ALQUILER_FEC_INI], [PAGO_ALQUILER_FEC_FIN], [PAGO_ALQUILER_IMPORTE],
[PAGO_ALQUILER_MEDIO_PAGO]
from [gd_esquema].[Maestra]
WHERE ALQUILER_CODIGO IS NOT NULL
select * from LOS_GESTIONADORES.Pago_Alquiler

select distinct [AGENTE_DNI], [AGENTE_NOMBRE], [AGENTE_APELLIDO], [AGENTE_TELEFONO], [AGENTE_FECHA_REGISTRO], [AGENTE_MAIL],
[AGENTE_FECHA_NAC]
from [gd_esquema].[Maestra]
WHERE [AGENTE_DNI] IS NOT NULL
select * from LOS_GESTIONADORES.Agente 

select distinct SUCURSAL_CODIGO, [SUCURSAL_NOMBRE], [SUCURSAL_DIRECCION], [SUCURSAL_TELEFONO], [SUCURSAL_LOCALIDAD], 
[SUCURSAL_PROVINCIA]
from [gd_esquema].[Maestra]
WHERE SUCURSAL_CODIGO IS NOT NULL
select * from LOS_GESTIONADORES.Sucursal

select distinct VENTA_CODIGO, [VENTA_FECHA], [VENTA_PRECIO_VENTA], [VENTA_COMISION]
from [gd_esquema].[Maestra]
WHERE VENTA_CODIGO IS NOT NULL
select * from LOS_GESTIONADORES.Venta

select distinct [COMPRADOR_DNI], [COMPRADOR_FECHA_REGISTRO], [COMPRADOR_TELEFONO], [COMPRADOR_MAIL], [COMPRADOR_FECHA_NAC]
from [gd_esquema].[Maestra]
WHERE [COMPRADOR_DNI] IS NOT NULL
select * from LOS_GESTIONADORES.Comprador

select [PAGO_VENTA_IMPORTE], [PAGO_VENTA_MONEDA], [PAGO_VENTA_COTIZACION], [PAGO_VENTA_MEDIO_PAGO]
from [gd_esquema].[Maestra]
WHERE [PAGO_VENTA_IMPORTE] IS NOT NULL
select * from LOS_GESTIONADORES.Pago_Venta

/*VER INQUILINO UNA FILA MAS*/
select DISTINCT INQUILINO_DNI, [INQUILINO_NOMBRE], [INQUILINO_APELLIDO], [INQUILINO_FECHA_REGISTRO], [INQUILINO_TELEFONO],
[INQUILINO_MAIL], [INQUILINO_FECHA_NAC]
from [gd_esquema].[Maestra]
WHERE INQUILINO_DNI IS NOT NULL
select * from LOS_GESTIONADORES.Inquilino

/*VER DETALLE PERIODO*/
select DISTINCT ALQUILER_CODIGO, DETALLE_ALQ_NRO_PERIODO_FIN, DETALLE_ALQ_NRO_PERIODO_INI, DETALLE_ALQ_PRECIO
from [gd_esquema].[Maestra]
WHERE DETALLE_ALQ_NRO_PERIODO_FIN IS NOT NULL AND DETALLE_ALQ_NRO_PERIODO_INI IS NOT NULL
select * from LOS_GESTIONADORES.Detalle_Importe
--WHERE alquiler_id = 152990
select * from LOS_GESTIONADORES.Tipo_Operacion

SELECT * FROM [LOS_GESTIONADORES].[Tipo_Ambiente]

SELECT YEAR(fecha_publicacion) FROM [LOS_GESTIONADORES].anuncio

